base:
  project: simple-dvc-project
  random_state: 1429
  target_col: quality
  test_size: 0.2

data_source:
  s3_source: C:\Users\bishw\OneDrive\Documents\winequality-red.csv

artifacts:
  artifacts_dir: artifacts
  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/data.csv
  split_date:
    processed_data_dir: artifacts/processed_data
    train_path: artifacts/processed_data/train.csv
    test_path: artifacts/processed_data/test.csv

  reports:
    reports_dir: artifacts/reports
    params: artifacts/reports/params.json
    scores: artifacts/reports/scores.json

  model_dir: artifacts/saved_models
  model_path: artifacts/saved_models/model.joblib

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

